// File generated by Antigravity based on user provided Firebase config for project: aphomeservices-5ws1oh
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7ITslgTJT_X2yMTB8L8C9iljlB7HctGk',
    appId: '1:888601961403:web:c5384904491366a49d5a9e',
    messagingSenderId: '888601961403',
    projectId: 'aphomeservices-5ws1oh',
    authDomain: 'aphomeservices-5ws1oh.firebaseapp.com',
    storageBucket: 'aphomeservices-5ws1oh.firebasestorage.app',
  );

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyC8qDhsCwyCFTwwf9grfTm2i7pPtV-KFkw',
  appId: '1:888601961403:android:5dab37b81572425e9d5a9e',
  messagingSenderId: '888601961403',
  projectId: 'aphomeservices-5ws1oh',
  storageBucket: 'aphomeservices-5ws1oh.firebasestorage.app',
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ITslgTJT_X2yMTB8L8C9iljlB7HctGk',
    appId: '1:888601961403:ios:e254f85e45c71fcadf33bfad2', // Fallback placeholder
    messagingSenderId: '888601961403',
    projectId: 'aphomeservices-5ws1oh',
    storageBucket: 'aphomeservices-5ws1oh.firebasestorage.app',
    iosBundleId: 'com.example.zeerah',
  );
}
